services:
  portfolio:
    build: .
    volumes:
      - "./html:/home/saurabh/Tasks/Webs/My-Portfolio/html"
  simple_http_server:
     image: pareshpawar/simple-http-server:latest

  nginx:
     image: nginx:latest
     ports:
        - "80:80"
     volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
        - portfolio
        - simple_http_server  